//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBet.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoBet.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is already locked.
        /// </summary>
        public static string ACCOUNT_ALREADY_LOCKED {
            get {
                return ResourceManager.GetString("ACCOUNT_ALREADY_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account was just locked..
        /// </summary>
        public static string ACCOUNT_NOW_LOCKED {
            get {
                return ResourceManager.GetString("ACCOUNT_NOW_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account must undergo password recovery to reactivate via https://identitysso.betfair.com/view/recoverpassword.
        /// </summary>
        public static string ACCOUNT_PENDING_PASSWORD_CHANGE {
            get {
                return ResourceManager.GetString("ACCOUNT_PENDING_PASSWORD_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must login to https://www.betfair.com to provide missing information..
        /// </summary>
        public static string ACTIONS_REQUIRED {
            get {
                return ResourceManager.GetString("ACTIONS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Client Master.
        /// </summary>
        public static string AGENT_CLIENT_MASTER {
            get {
                return ResourceManager.GetString("AGENT_CLIENT_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended Agent Client Master.
        /// </summary>
        public static string AGENT_CLIENT_MASTER_SUSPENDED {
            get {
                return ResourceManager.GetString("AGENT_CLIENT_MASTER_SUSPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to login to the Betfair Romania domain with a non.ro account.
        /// </summary>
        public static string AUTHORIZED_ONLY_FOR_DOMAIN_RO {
            get {
                return ResourceManager.GetString("AUTHORIZED_ONLY_FOR_DOMAIN_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to login to the Betfair Swedish domain with a non.se account..
        /// </summary>
        public static string AUTHORIZED_ONLY_FOR_DOMAIN_SE {
            get {
                return ResourceManager.GetString("AUTHORIZED_ONLY_FOR_DOMAIN_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is accessed from a location where betting is restricted.
        /// </summary>
        public static string BETTING_RESTRICTED_LOCATION {
            get {
                return ResourceManager.GetString("BETTING_RESTRICTED_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate required or certificate present but could not authenticate with it.
        /// </summary>
        public static string CERT_AUTH_REQUIRED {
            get {
                return ResourceManager.GetString("CERT_AUTH_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password required.
        /// </summary>
        public static string CHANGE_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is closed.
        /// </summary>
        public static string CLOSED {
            get {
                return ResourceManager.GetString("CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country code must have 2 characters..
        /// </summary>
        public static string COUNTRY_CODE_CHAR_LENGTH {
            get {
                return ResourceManager.GetString("COUNTRY_CODE_CHAR_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish authorization required.
        /// </summary>
        public static string DANISH_AUTHORIZATION_REQUIRED {
            get {
                return ResourceManager.GetString("DANISH_AUTHORIZATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark migration required.
        /// </summary>
        public static string DENMARK_MIGRATION_REQUIRED {
            get {
                return ResourceManager.GetString("DENMARK_MIGRATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate cards.
        /// </summary>
        public static string DUPLICATE_CARDS {
            get {
                return ResourceManager.GetString("DUPLICATE_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has not opted in to log in with the email.
        /// </summary>
        public static string EMAIL_LOGIN_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("EMAIL_LOGIN_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email must be valid..
        /// </summary>
        public static string EMAIL_MUST_BE_VALID {
            get {
                return ResourceManager.GetString("EMAIL_MUST_BE_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest international terms and conditions must be accepted prior to logging in..
        /// </summary>
        public static string INTERNATIONAL_TERMS_ACCEPTANCE_REQUIRED {
            get {
                return ResourceManager.GetString("INTERNATIONAL_TERMS_ACCEPTANCE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DK regulator cannot be accessed due to some internal problems in the system behind or in at regulator; timeout cases included..
        /// </summary>
        public static string INVALID_CONNECTIVITY_TO_REGULATOR_DK {
            get {
                return ResourceManager.GetString("INVALID_CONNECTIVITY_TO_REGULATOR_DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IT regulator cannot be accessed due to some internal problems in the system behind or in at regulator; timeout cases included..
        /// </summary>
        public static string INVALID_CONNECTIVITY_TO_REGULATOR_IT {
            get {
                return ResourceManager.GetString("INVALID_CONNECTIVITY_TO_REGULATOR_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password are invalid.
        /// </summary>
        public static string INVALID_USERNAME_OR_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_USERNAME_OR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest Italian contract version must be accepted.You must login to the website to accept the new conditions..
        /// </summary>
        public static string ITALIAN_CONTRACT_ACCEPTANCE_REQUIRED {
            get {
                return ResourceManager.GetString("ITALIAN_CONTRACT_ACCEPTANCE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must login to the website to accept the new conditions.
        /// </summary>
        public static string ITALIAN_PROFILING_ACCEPTANCE_REQUIRED {
            get {
                return ResourceManager.GetString("ITALIAN_PROFILING_ACCEPTANCE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KYC suspended.
        /// </summary>
        public static string KYC_SUSPEND {
            get {
                return ResourceManager.GetString("KYC_SUSPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organization locality/city field must not contain any special characters..
        /// </summary>
        public static string LOCALITY_FIELD_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("LOCALITY_FIELD_SPECIAL_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is more than one account with the same credential.
        /// </summary>
        public static string MULTIPLE_USERS_WITH_SAME_CREDENTIAL {
            get {
                return ResourceManager.GetString("MULTIPLE_USERS_WITH_SAME_CREDENTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field must not be empty..
        /// </summary>
        public static string NAME_FIELD_EMPTY {
            get {
                return ResourceManager.GetString("NAME_FIELD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field must not contain any special character..
        /// </summary>
        public static string NAME_FIELD_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("NAME_FIELD_SPECIAL_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user identified by the given credentials is not authorized in the DK&apos;s jurisdictions due to the regulators&apos; policies.Ex: the user for which this session should be created is not allowed to act(play, bet) in the DK&apos;s jurisdiction..
        /// </summary>
        public static string NOT_AUTHORIZED_BY_REGULATOR_DK {
            get {
                return ResourceManager.GetString("NOT_AUTHORIZED_BY_REGULATOR_DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user identified by the given credentials is not authorized in the IT&apos;s jurisdictions due to the regulators&apos; policies.Ex: the user for which this session should be created is not allowed to act(play, bet) in the IT&apos;s jurisdiction..
        /// </summary>
        public static string NOT_AUTHORIZED_BY_REGULATOR_IT {
            get {
                return ResourceManager.GetString("NOT_AUTHORIZED_BY_REGULATOR_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organization name field must not contain any special characters..
        /// </summary>
        public static string ORGANIZATION_FIELD_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("ORGANIZATION_FIELD_SPECIAL_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organizational unit name field must not contain any special characters..
        /// </summary>
        public static string ORGANIZATION_UNIT_FIELD_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("ORGANIZATION_UNIT_FIELD_SPECIAL_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be provided..
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending authentication.
        /// </summary>
        public static string PENDING_AUTH {
            get {
                return ResourceManager.GetString("PENDING_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal message required for the user.
        /// </summary>
        public static string PERSONAL_MESSAGE_REQUIRED {
            get {
                return ResourceManager.GetString("PERSONAL_MESSAGE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember credentials.
        /// </summary>
        public static string REMEMBER_CREDENTIALS {
            get {
                return ResourceManager.GetString("REMEMBER_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has entered wrong the security answer 3 times.
        /// </summary>
        public static string SECURITY_QUESTION_WRONG_3X {
            get {
                return ResourceManager.GetString("SECURITY_QUESTION_WRONG_3X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is restricted due to security concerns.
        /// </summary>
        public static string SECURITY_RESTRICTED_LOCATION {
            get {
                return ResourceManager.GetString("SECURITY_RESTRICTED_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has been self-excluded.
        /// </summary>
        public static string SELF_EXCLUDED {
            get {
                return ResourceManager.GetString("SELF_EXCLUDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SIGN_IN {
            get {
                return ResourceManager.GetString("SIGN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain migration required.
        /// </summary>
        public static string SPAIN_MIGRATION_REQUIRED {
            get {
                return ResourceManager.GetString("SPAIN_MIGRATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest Spanish terms and conditions version must be accepted. You must login to the website to accept the new conditions..
        /// </summary>
        public static string SPANISH_TERMS_ACCEPTANCE_REQUIRED {
            get {
                return ResourceManager.GetString("SPANISH_TERMS_ACCEPTANCE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state/province field must not contain any special characters..
        /// </summary>
        public static string STATE_FIELD_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("STATE_FIELD_SPECIAL_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authenticated successfully..
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is suspended.
        /// </summary>
        public static string SUSPENDED {
            get {
                return ResourceManager.GetString("SUSPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provided your Swedish bank id via Betfair.se before proceeding..
        /// </summary>
        public static string SWEDEN_BANK_ID_VERIFICATION_REQUIRED {
            get {
                return ResourceManager.GetString("SWEDEN_BANK_ID_VERIFICATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provided your Swedish National identifier via Betfair.se before proceeding..
        /// </summary>
        public static string SWEDEN_NATIONAL_IDENTIFIER_REQUIRED {
            get {
                return ResourceManager.GetString("SWEDEN_NATIONAL_IDENTIFIER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telbet terms and conditions rejected.
        /// </summary>
        public static string TELBET_TERMS_CONDITIONS_NA {
            get {
                return ResourceManager.GetString("TELBET_TERMS_CONDITIONS_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit for successful login requests per minute has been exceeded.New login attempts will be banned for 20 minutes.
        /// </summary>
        public static string TEMPORARY_BAN_TOO_MANY_REQUESTS {
            get {
                return ResourceManager.GetString("TEMPORARY_BAN_TOO_MANY_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Master Account.
        /// </summary>
        public static string TRADING_MASTER {
            get {
                return ResourceManager.GetString("TRADING_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended Trading Master Account.
        /// </summary>
        public static string TRADING_MASTER_SUSPENDED {
            get {
                return ResourceManager.GetString("TRADING_MASTER_SUSPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username must be provided..
        /// </summary>
        public static string USERNAME_EMPTY {
            get {
                return ResourceManager.GetString("USERNAME_EMPTY", resourceCulture);
            }
        }
    }
}
